run:
  timeout: 5m
  skip-dirs:
  - pkg/clientset
  - config/
  - third_party/
linters:
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - errorlint
  - exhaustive
  - exportloopref
  - gci
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - structcheck
  - typecheck
  - unconvert
  - unparam
  - varcheck
  - wastedassign
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kong/gateway-operator)
  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/api/apps/v1
        alias: appsv1
      - pkg: k8s.io/api/admission/v1
        alias: admissionv1
      - pkg: k8s.io/api/certificates/v1
        alias: certificatesv1

      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: sigs.k8s.io/gateway-api/apis/(v[\w\d]+)
        alias: gateway${1}
issues:
  fix: true
