# permissions for end users to view gatewayconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewayconfiguration-viewer-role
rules:
- apiGroups:
  - gateway-operator.gateway-operator.konghq.com
  resources:
  - gatewayconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway-operator.gateway-operator.konghq.com
  resources:
  - gatewayconfigurations/status
  verbs:
  - get
